[package]
extra-files = [
    "%{_mandir}/man1/%{crate}.1*",
    "%{bash_completions_dir}/%{crate}.bash",
    "%{zsh_completions_dir}/_%{crate}",
    "%{fish_completions_dir}/%{crate}.fish",
]
 
[scripts]
install.post = [
    "# install man page",
    "install -Dpm0644 target/release/build/%{crate}-*/out/%{crate}.1 \\",
    "    -t %{buildroot}%{_mandir}/man1/",
    "# install shell completions",
    "install -Dpm0644 target/release/build/%{crate}-*/out/%{crate}.bash \\",
    "    %{buildroot}/%{bash_completions_dir}/%{crate}.bash",
    "install -Dpm0644 target/release/build/%{crate}-*/out/%{crate}.fish \\",
    "    %{buildroot}/%{fish_completions_dir}/%{crate}.fish",
    "install -Dpm0644 target/release/build/%{crate}-*/out/_%{crate} \\",
    "    %{buildroot}/%{zsh_completions_dir}/_%{crate}",
]
 
