# Generated by rust2rpm 28
%bcond check 1

%global debug_package %{nil}

# prevent library files from being installed
%global cargo_install_lib 0

%global crate dysk

Name:           rust-dysk
Version:        3.6.0
Release:        %autorelease -e 2
Summary:        Give information on mounted filesystems

License:        MIT
URL:            https://crates.io/crates/dysk
Source:         %{crates_source}
Source:         https://github.com/RebornRider/copr-packages/releases/download/source-artefacts/dysk-3.6.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Give information on mounted filesystems.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND MIT AND (MIT OR Apache-2.0) AND (Unlicense OR MIT)
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/dysk
%{_mandir}/man1/%{crate}.1*
%{bash_completions_dir}/%{crate}.bash
%{zsh_completions_dir}/_%{crate}
%{fish_completions_dir}/%{crate}.fish

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
# install man page
install -Dpm0644 target/release/build/%{crate}-*/out/%{crate}.1 \
    -t %{buildroot}%{_mandir}/man1/
# install shell completions
install -Dpm0644 target/release/build/%{crate}-*/out/%{crate}.bash \
    %{buildroot}/%{bash_completions_dir}/%{crate}.bash
install -Dpm0644 target/release/build/%{crate}-*/out/%{crate}.fish \
    %{buildroot}/%{fish_completions_dir}/%{crate}.fish
install -Dpm0644 target/release/build/%{crate}-*/out/_%{crate} \
    %{buildroot}/%{zsh_completions_dir}/_%{crate}

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
