# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}

# https://github.com/Xuanwo/go-locale
%global goipath         github.com/Xuanwo/go-locale
Version:                1.1.3

%gometa -L -f

%global common_description %{expand:
Cross platform locale detection for Golang.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           golang-github-xuanwo-locale
Release:        %autorelease
Summary:        Cross platform locale detection for Golang

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
