[package]
extra-files = [
    "%{_mandir}/man1/%{crate}.1*",
    "%{_mandir}/man5/%{crate}_colors*",
    "%{bash_completions_dir}/%{crate}",
    "%{zsh_completions_dir}/_%{crate}",
    "%{fish_completions_dir}/%{crate}.fish",
]

#[features]
#enable-all = true

[requires] 
build = [
    "pandoc",
]
 
[scripts]
install.post = [
 	"# install man pages",
 	"mkdir target/man",
 	"sed \"s/\\$version/v%{version}/g\" man/%{crate}.1.md | pandoc --standalone -f markdown -t man > target/man/%{crate}.1",
 	"sed \"s/\\$version/v%{version}/g\" man/%{crate}_colors.5.md | pandoc --standalone -f markdown -t man > target/man/%{crate}_colors.5",
 	"sed \"s/\\$version/v%{version}/g\" man/%{crate}_colors-explanation.5.md | pandoc --standalone -f markdown -t man > target/man/%{crate}_colors-explanation.5",
    "install -Dpm0644 target/man/%{crate}.1 \\",
    "    -t %{buildroot}/%{_mandir}/man1/",
    "install -Dpm0644 target/man/%{crate}_colors.5 \\",
    "    -t %{buildroot}/%{_mandir}/man5/",
    "install -Dpm0644 target/man/%{crate}_colors-explanation.5 \\",
    "    -t %{buildroot}/%{_mandir}/man5/",
    "# install shell completions",
    "install -Dpm0644 completions/bash/%{crate} \\",
    "    -t %{buildroot}/%{bash_completions_dir}/}",
    "install -Dpm0644 completions/fish/%{crate}.fish \\",
    "    -t %{buildroot}/%{fish_completions_dir}/",
    "install -Dpm0644 completions/zsh/_%{crate} \\",
    "    -t %{buildroot}/%{zsh_completions_dir}/",
]
 
