# Generated by go2rpm 1.9.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}

# https://github.com/djherbis/times
%global goipath         github.com/djherbis/times
Version:                1.6.0

%gometa -L -f

%global common_description %{expand:
golang file times (atime, mtime, ctime, btime).}

%global golicenses      LICENSE
%global godocs          example README.md

Name:           golang-github-djherbis-times
Release:        %autorelease
Summary:        golang file times (atime, mtime, ctime, btime)

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
