# Generated by go2rpm 1.16.0
%bcond check 1

# https://github.com/charmbracelet/glow
%global goipath         github.com/charmbracelet/glow
Version:                2.1.1

%gometa -L -f

%global common_description %{expand:
Render markdown on the CLI, with pizzazz!.}

Name:           glow
Release:        %autorelease
Summary:        Render markdown on the CLI, with pizzazz!

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description %{common_description}

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%gobuild -o %{gobuilddir}/bin/glow %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/%{name} %{buildroot}%{_bindir}/

# Shell completions
%{gobuilddir}/bin/%{name} completion bash > %{name}.bash
install -Dpm 0644 %{name}.bash -t %{buildroot}/%{bash_completions_dir}
%{gobuilddir}/bin/%{name} completion zsh > _%{name}
install -Dpm 0644 _%{name} -t %{buildroot}/%{zsh_completions_dir}
%{gobuilddir}/bin/%{name} completion fish > %{name}.fish
install -Dpm 0644 %{name}.fish -t %{buildroot}/%{fish_completions_dir}

# man page
%{gobuilddir}/bin/%{name} man > %{name}.1
install -Dpm 0644 %{name}.1 -t %{buildroot}%{_mandir}/man1/


%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gocheck
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1*
%{bash_completions_dir}/%{name}.bash
%{zsh_completions_dir}/_%{name}
%{fish_completions_dir}/%{name}.fish


%changelog
%autochangelog
